// <auto-generated />
using CV_generator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CV__generator.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250729165616_CV Generators")]
    partial class CVGenerators
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CV_generator.Models.ResumeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("CV_generator.Models.ResumeData", b =>
                {
                    b.OwnsMany("CV_generator.Models.Education", "Education", b1 =>
                        {
                            b1.Property<int>("ResumeDataId")
                                .HasColumnType("int");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Degree")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Details")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("University")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Year")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ResumeDataId", "__synthesizedOrdinal");

                            b1.ToTable("Resumes");

                            b1.ToJson("Education");

                            b1.WithOwner()
                                .HasForeignKey("ResumeDataId");
                        });

                    b.OwnsMany("CV_generator.Models.Experience", "Experience", b1 =>
                        {
                            b1.Property<int>("ResumeDataId")
                                .HasColumnType("int");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Company")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.PrimitiveCollection<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Years")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ResumeDataId", "__synthesizedOrdinal");

                            b1.ToTable("Resumes");

                            b1.ToJson("Experience");

                            b1.WithOwner()
                                .HasForeignKey("ResumeDataId");
                        });

                    b.OwnsOne("CV_generator.Models.Personal", "Personal", b1 =>
                        {
                            b1.Property<int>("ResumeDataId")
                                .HasColumnType("int");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("GitHub")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LinkedIn")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ResumeDataId");

                            b1.ToTable("Resumes");

                            b1.WithOwner()
                                .HasForeignKey("ResumeDataId");
                        });

                    b.OwnsMany("CV_generator.Models.Project", "Projects", b1 =>
                        {
                            b1.Property<int>("ResumeDataId")
                                .HasColumnType("int");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Link")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ResumeDataId", "__synthesizedOrdinal");

                            b1.ToTable("Resumes");

                            b1.ToJson("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ResumeDataId");
                        });

                    b.Navigation("Education");

                    b.Navigation("Experience");

                    b.Navigation("Personal")
                        .IsRequired();

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
